### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'bioformats' distribution was not found and is required by chromosomer

### ISSUE THREAD

**Issue by Mayankguptai** [gtamazian/chromosomer#19]
Hey!

I am using chromosomer and installed it using pip install and still I am getting following errors-

Traceback (most recent call last):
  File "/home/mayank/anaconda/bin/chromosomer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 3084, in <module>
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 3070, in _call_aside
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 952, in require
  File "/home/mayank/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'bioformats' distribution was not found and is required by chromosomer

Any suggestions?

Thanks
Mayank

**Comment by gtamazian** [comment]
Hello Mayank,

Please try to install package `bioformats` explicitly:

```
pip2 install bioformats
```

If it does not work, I would advise to create a separate virtual environment and install Chromosomer to it. You may use package [virtuanenvwrapper](virtualenvwrapper.readthedocs.io) for that purpose:

```
mkvirtualenv --python=python2.7 chromosomer
pip2 install chromosomer
```

**Comment by Mayankguptai** [comment]
Thanks it is working now in virtual environment
